
version: '2'

services:
  db:
    image: mariadb
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: *******
      MYSQL_PASSWORD: *********

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: *******
      MYSQL_PASSWORD: ***********
    volumes:
      - nextcloud:/var/www/html

volumes:
  db:
  nextcloud:  

